      - name: Deploy Contract
        run: |
          ls -la src/
          forge create --rpc-url "${{ secrets.ALCHEMY_BASE_RPC_URL }}" --private-key "${{ secrets.PRIVATE_KEY }}" src/BaseAtomicArbitrage.sol:BaseAtomicArbitrage --constructor-args 0x63Fd24a09B2d8eAa2eb16277B7C3B17512294143 --broadcast
