name: Deploy BaseAtomicArbitrage

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy-contract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest

      - name: Run Foundry Tests
        run: forge test -vvv

      - name: Deploy to Base Mainnet
        env:
          RPC: ${{ secrets.ALCHEMY_BASE_RPC_URL }}
          KEY: ${{ secrets.PRIVATE_KEY }}
          ARG: 0x63Fd24a09B2d8eAa2eb16277B7C3B17512294143
        run: |
          echo "Deploying contract to Base Mainnet..."
          forge create --rpc-url "$RPC" \
            --private-key "$KEY" \
            src/BaseAtomicArbitrage.sol:BaseAtomicArbitrage \
            --constructor-args "$ARG" \
            --verify
